import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { ReportData } from '../../shared/types';

function formatDuration(seconds: number): string {
  if (seconds < 60) return `${Math.round(seconds)}s`;
  if (seconds < 3600) return `${Math.round(seconds / 60)}m`;
  const h = Math.floor(seconds / 3600);
  const m = Math.round((seconds % 3600) / 60);
  return `${h}h ${m}m`;
}

function formatTime(iso: string): string {
  if (!iso) return '—';
  return new Date(iso).toLocaleTimeString();
}

export async function generatePDFReport(data: ReportData): Promise<void> {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 18;

  // Header
  doc.setFillColor(0, 122, 204);
  doc.rect(0, 0, pageWidth, 12, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('Sonar Code Editor — Activity Report', 14, 8);

  y = 22;
  doc.setTextColor(30, 30, 30);
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text(`Team: ${data.team.teamName}`, 14, y);
  y += 7;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 100, 100);
  if (data.sessionStart) {
    doc.text(`Session: ${new Date(data.sessionStart).toLocaleDateString()}  ${formatTime(data.sessionStart)} → ${formatTime(data.sessionEnd)}`, 14, y);
    y += 5;
  }
  doc.text(`Generated: ${new Date().toLocaleString()}`, 14, y);
  y += 10;

  // Summary
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(30, 30, 30);
  doc.text('Summary', 14, y);
  y += 5;

  const summaryData = [
    ['Total Session Duration', formatDuration(data.summary.totalDuration)],
    ['Online Time', formatDuration(data.summary.totalOnlineTime)],
    ['Offline Time', formatDuration(data.summary.totalOfflineTime)],
    ['% Time Online', `${data.summary.percentOnline}%`],
    ['% Time in IDE', `${data.summary.percentInIDE}%`],
    ['Disconnections', String(data.summary.disconnections)],
    ['App Switches', String(data.summary.appSwitches)],
    ['Longest Online Stretch', formatDuration(data.summary.longestOnlineStretch)],
  ];

  autoTable(doc, {
    startY: y,
    head: [['Metric', 'Value']],
    body: summaryData,
    theme: 'striped',
    headStyles: { fillColor: [0, 122, 204] },
    styles: { fontSize: 10 },
    margin: { left: 14, right: 14 },
  });

  y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 10;

  // Status Timeline
  if (data.statusTimeline.length > 0) {
    if (y > 240) { doc.addPage(); y = 18; }
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(30, 30, 30);
    doc.text('Online/Offline Timeline', 14, y);
    y += 5;

    autoTable(doc, {
      startY: y,
      head: [['Status', 'From', 'To', 'Duration']],
      body: data.statusTimeline.map((e) => [
        e.status.toUpperCase(),
        formatTime(e.from),
        formatTime(e.to),
        formatDuration(e.duration),
      ]),
      theme: 'striped',
      headStyles: { fillColor: [0, 122, 204] },
      styles: { fontSize: 9 },
      bodyStyles: {},
      didParseCell: (hookData) => {
        if (hookData.column.index === 0) {
          const val = (hookData.cell.raw as string).toLowerCase();
          if (val === 'online') hookData.cell.styles.textColor = [76, 175, 80];
          if (val === 'offline') hookData.cell.styles.textColor = [244, 67, 54];
        }
      },
      margin: { left: 14, right: 14 },
    });

    y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 10;
  }

  // App Usage
  if (data.appUsage.length > 0) {
    if (y > 220) { doc.addPage(); y = 18; }
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(30, 30, 30);
    doc.text('Application Usage', 14, y);
    y += 5;

    autoTable(doc, {
      startY: y,
      head: [['App', 'Window Title', 'First Seen', 'Last Seen', 'Total Time', 'Flag']],
      body: data.appUsage.map((e) => [
        e.appName,
        e.windowTitle ? e.windowTitle.substring(0, 40) : '—',
        formatTime(e.firstSeen),
        formatTime(e.lastSeen),
        formatDuration(e.totalTime),
        e.appName !== 'Sonar Code Editor' ? '⚠ Non-IDE' : '',
      ]),
      theme: 'striped',
      headStyles: { fillColor: [0, 122, 204] },
      styles: { fontSize: 9 },
      margin: { left: 14, right: 14 },
    });
  }

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(`Generated by Sonar Code Editor — Page ${i} of ${pageCount}`, 14, doc.internal.pageSize.getHeight() - 8);
  }

  // Download
  doc.save(`report_${data.team.teamName}_${new Date().toISOString().split('T')[0]}.pdf`);
}
